# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c42d758134b1f017cf3a58ef71a6b074fee4826485d78b2cdf44462800f0bc13b75a9f690430bab783aa99bc753afbfbd20163ded5ebc1fc97d305dc40d08604

test:
  secret_key_base: 243d0c1062a6c05855650e53b313376047ddc3353ab62df8679d5cd0c80fc99e8c14d8a0248707e66c642aa12965a1c8da5bf057f3791f8c2ff62311cedc941b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
